name: Build and pack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore nuget packages
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Benchmarks
      run: dotnet run --no-build --configuration Release --project Pidgin.Bench/Pidgin.Bench.csproj -- -f '*'
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release -o nupkgs
      
    - uses: nikeee/docfx-action@v1.0.0
      with:
        args: Pidgin.Docs/docfx.json
      
    - uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: nupkgs
    
    - uses: actions/upload-artifact@v2
      with:
        name: BenchmarkDotNet.Artifacts
        path: BenchmarkDotNet.Artifacts
    
    - uses: actions/upload-artifact@v2
      with:
        name: Pidgin.Docs
        path: Pidgin.Docs/_site
